### ISSUE TITLE
引入vConsole最新版本3.14.6不好用，这个是什么原因呢

### ISSUE THREAD

**Issue by ccj** [whistle-plugins/examples#11]
https://github.com/Tencent/vConsole
引入vConsole最新版本3.14.6不好用，这个是什么原因呢

**Comment by avwo** [comment]
具体什么问题

**Comment by ccj** [comment]
没有展示vConsole的按钮，你example里的vConsole版本v3.3.4展示了。不过这个版本稍微有点低。

**Comment by avwo** [comment]
是不是 vconsole 初始化逻辑改了，你看下 js 没有报错

**Comment by ccj** [comment]
谢谢，已经可以了
